version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: newsroom-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: newsroom
    volumes:
      - mongodb_data:/data/db
    networks:
      - newsroom-network

  # Backend API (Spring Boot)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: newsroom-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/newsroom
      - SPRING_DATA_MONGODB_DATABASE=newsroom
    depends_on:
      - mongodb
    networks:
      - newsroom-network

  # Frontend (Next.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: newsroom-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080/api
    depends_on:
      - backend
    networks:
      - newsroom-network

volumes:
  mongodb_data:
    driver: local

networks:
  newsroom-network:
    driver: bridge

