server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/newsroom
      database: newsroom

  application:
    name: newsroom-backend

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC

app:
  jwt:
    secret: vSEjy7qQU+ZJLv4efKkWnaPBR5PePmWwdHBXAF5MJE9GwYmTl9/fwgHfUhExSL0gRB3JGlhR6F6sf25j5FkdPQ==
    expiration-access-token: 600
    expiration-refresh-token: 86400000
  cors:
    allowed-origins: "http://localhost:3000"
  base-url: "http://localhost:8080"

file:
  upload-dir: uploads

logging:
  level:
    com.newsroom: DEBUG
    org.springframework.web: INFO
    org.springframework.data.mongodb: DEBUG
